export type {
  default as GameCategoryDef,
  GameCategoryId,
} from "./categories";
export {
  GAME_CODE_ALPHABET,
  GAME_CODE_LENGTH,
  gameCodeSchema,
  generateGameCode,
  isGameCode,
  normalizeGameCode,
} from "./code";
export { type GameType, gameTypeSchema } from "./core";
export type {
  ConfigField,
  ConfigFieldType,
  GameDefinition,
  GameMeta,
} from "./definition";
export type {
  GameEngine,
  MoveContext,
  Outcome,
  ReduceResult,
  Seat,
  StepResult,
} from "./engine";
export {
  buildGameResultViewModel,
  type GameResultOutcome,
  type GameResultPhase,
  type GameResultPlayer,
  type GameResultPrimaryAction,
  type GameResultViewModel,
  isMatchSeriesComplete,
  type MatchConfig,
  type MatchFormat,
  type PlayerSessionStats,
  resolveMatchConfig,
} from "./result";
export {
  type SeriesDetail,
  type SeriesGameSummary,
  type SeriesScore,
  type SeriesScoreEntry,
  seriesDetailSchema,
  seriesGameSummarySchema,
  seriesScoreEntrySchema,
  seriesScoreSchema,
} from "./series";
export {
  type Cell,
  type Mark,
  type TicTacToeConfig,
  type TicTacToeMove,
  type TicTacToeState,
  ticTacToeConfigSchema,
  ticTacToeMoveSchema,
  ticTacToeStateSchema,
} from "./tic-tac-toe/schemas";
export {
  type ClientCreateRoom,
  type ClientJoinByCode,
  type ClientJoinRoom,
  type ClientMakeMove,
  type ClientQueueJoin,
  type ClientQueueLeave,
  clientCreateRoomSchema,
  clientJoinByCodeSchema,
  clientJoinRoomSchema,
  clientMakeMoveSchema,
  clientQueueJoinSchema,
  clientQueueLeaveSchema,
  type GameJson,
  type GamePlayerDto,
  type GameStatusDto,
  gameJsonSchema,
  gamePlayerSchema,
  gameStatusSchema,
  isGameLive,
  isGameOver,
  type JoinByCodeError,
  joinByCodeErrorSchema,
  type MoveJson,
  moveJsonSchema,
  resolveWinnerUsername,
  type SeatingModeDto,
  type ServerErrorPayload,
  type ServerGameOverPayload,
  type ServerGameStatePayload,
  type ServerJoinByCodeResult,
  type ServerMatchFoundPayload,
  type ServerRoomCreatedPayload,
  seatingModeSchema,
} from "./wire";
